INSERT INTO subject  VALUES (1,'123','admin');
INSERT INTO grupo VALUES (1,'ADMINISTRADORES'),(2,'SECRETARIOS'),(3,'COORDENADORES'),(4,'DIRECAO'),(5,'VIGILANTES'),(6,'TERCEIRIZADOS'),(7,'BIBLIOTECA');
INSERT INTO subject_group VALUES (1,1)
select setval('', 1);